Try reading GITHUB_EVENT_PATH

diff --git a/.github/workflows/build-nvidia.yml b/.github/workflows/build-nvidia.yml
--- a/.github/workflows/build-nvidia.yml
+++ b/.github/workflows/build-nvidia.yml
@@ -78,6 +78,17 @@ jobs:
     needs: [build]
     if: ${{ github.event_name == 'pull_request' }}
     steps:
-      - name: Exit
-        shell: bash
-        run: exit 0
+      - name: Output some debug information
+        run: |
+          cat $GITHUB_EVENT_PATH
+
+      - name: Check Matrix Job Status
+        id: matrix-status
+        run: |
+          if [ -z "$(jq -r '.jobs | map(select(.conclusion != "success")) | .[] | .conclusion' $GITHUB_EVENT_PATH)" ]; then
+            echo "All matrix jobs were successful."
+            exit 0
+          else
+            echo "One or more matrix jobs failed."
+            exit 1
+          fi
